### ISSUE TITLE
Create da interview in dev HUD that creates foundational test files...

### ISSUE THREAD

**Issue by plocket** [plocket/al_story#5]
- [ ] to download
- [ ] and puts them in a manually given repo branch
- [ ] and puts them in the repo of the current interview

**Comment by BryceStevenWilley** [comment]
If I recall correctly, this is https://github.com/SuffolkLITLab/docassemble-ALKilnSetup, right? Is there something else to this issue?

**Comment by plocket** [comment]
I think this was to allow people to use al_story in a da interview to generate a test for an interview based on their JSON vars.

**Comment by BryceStevenWilley** [comment]
I thought that was https://github.com/plocket/al_story/issues/6, and that this one was for `.github/workflows/...`, and other misc things (at least that's how I understood"foundational"?). If they are both about generating test files specifically, they're probably dup issues

**Comment by plocket** [comment]
You're totally right, I was mixing these up. I'll close this, thanks!
